"""Render Topic 1 only, in the existing editor source and stable PDF filename."""
from pathlib import Path
import hashlib,json
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'analysis/out/pricing_adjustment';OUT=BASE/'topic1'
TEX=ROOT/'docs/reports/HK_IPO_2026_PRICING_AND_RETAIL_INFORMATION.tex'
MD=TEX.with_suffix('.md')
LABELS={'log_close':'Offer to close','log_opening':'Offer to opening','log_intraday':'Opening to close','log_mair_subscription':'HSI-adjusted close'}

def write_report():
 def read(name):return pd.read_csv(OUT/(name+'.csv'))
 expected='edaf79313313cd59b5bdd8a37f10d6ece383d47c89343ccc471564e19165f2d4'
 assert hashlib.sha256((BASE/'issuer_sample.csv').read_bytes()).hexdigest()==expected, 'Update the narrative before rendering a changed sample.'
 s=read('audited_issuer_panel');d=s[s.disclosure_class.eq('two_sided_range')]
 main=read('stage_inference');q=main[main.model.eq('quarter_controls')].set_index('outcome')
 raw=[];md=[];counter=0
 def esc(x):
  return str(x).replace('$',r'\$').replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
 def para(text):raw.append(esc(text)+'\n');md.append(text+'\n')
 def section(title):raw.append(r'\section*{'+esc(title)+'}\n');md.append('## '+title+'\n')
 def equation(text):raw.append('\\[\n'+text+'\n\\]\n');md.append('$$\n'+text+'\n$$\n')
 def page():raw.append(r'\clearpage'+'\n')
 def table(title,headers,rows,note=''):
  nonlocal counter;counter+=1
  raw.append(r'\par\addvspace{5pt}\textbf{Table '+str(counter)+'. '+esc(title)+r'}\par\nobreak\vspace{2pt}'+'\n')
  cols=r'p{.35\textwidth}X' if headers[-1]=='Assessment' else 'X'+'r'*(len(headers)-1)
  raw.append(r'{\small\renewcommand{\arraystretch}{1.10}\begin{tabularx}{\textwidth}{@{}'+cols+r'@{}}\toprule'+'\n')
  raw.append(' & '.join(r'\textbf{'+esc(h)+'}' for h in headers)+r' \\\midrule'+'\n')
  for row in rows:raw.append(' & '.join(esc(x) for x in row)+r' \\'+'\n')
  raw.append(r'\bottomrule\end{tabularx}}\par'+'\n')
  if note:raw.append(r'{\footnotesize '+esc(note)+r'}\par'+'\n')
  md.append('### Table '+str(counter)+'. '+title+'\n\n'+'| '+' | '.join(headers)+' |\n'+'| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(map(str,row))+' |\n' for row in rows)+'\n'+note+'\n')
 def pct(v):return f'{100*v:.2f}'
 def f3(v):return f'{v:.3f}'
 section('1. Question, answer and evidence boundary')
 para('Topic 1: Pricing adjustment and first-day returns. Hong Kong Main Board ordinary IPOs listed from 2 January to 30 September 2026. Prepared on 4 October 2026. This report completes the empirical assessment of the current sample. It does not claim to identify the cause of each price change. Research topics on retail prediction and allocation rules are separate.')
 para('Question: If the final offer price is high relative to the filed price range, why can a large gain still occur when trading starts? The data show that a price above the filed midpoint and a first-day gain can coexist. They also show large gains after pricing below the midpoint. A filed midpoint is a reference price, not an earlier agreed transaction price. Thus, the premise that the price was already increased during subscription is not established for these offers.')
 para('Main answer: The revision-return association is positive on the 43 range offers, but its size is uncertain. It survives changes in estimator and month deletion in sign. It does not pass the maintained multiple-test inference. Market-date sensitivity is much smaller than the effect of selecting firms with available pricing proxies. The data do not distinguish compensation for investor information from demand pressure, issuer selection, supply limits or other pricing choices.')
 groups=read('disclosure_groups').set_index('group')
 rows=[]
 for key,label in [('two_sided_range','Two-sided range'),('recorded_equal_endpoints','Recorded equal endpoints'),('confirmed_single_price','Single quoted price: 2041'),('confirmed_maximum_only','Confirmed maximum only')]:
  r=groups.loc[key];rows.append([label,int(r.n),int(r.ah_n),pct(r.mean_close),pct(r.median_close)])
 table('Audited classification and close returns',['Price evidence','N','A+H','Mean %','Median %'],rows,'Total N=113. The 31 previously missing-lower-bound cases were reviewed against complete official prospectuses: 30 maximum-only and one single-price offer. The other 39 equal-endpoint cases were not re-audited. All means are unweighted across IPOs; they are not account returns.')
 para('The main outcome is the offer-to-first-day-close return. Opening and intraday returns locate the trading stages. HSI adjustment is a sensitivity check. All primary price-stage equations use the same 43 firms and the same controls. A missing lower endpoint receives no invented midpoint and no zero revision.')
 equation(r'P_M=(P_L+P_H)/2,\quad v=P_0/P_M-1,\quad R_C=P_C/P_0-1,\\ R_O=P_O/P_0-1,\quad R_D=P_C/P_O-1.')
 para('PL and PH are the filed lower and upper prices. PM is their midpoint. P0 is the final offer price. PO and PC are the first trading-day opening and closing prices. Revision v compares final price with midpoint; it does not prove a dated price change. The 43 firms comprise 16 Q1, 14 Q2 and 13 Q3 listings; nine are A+H offers.')
 page();section('2. Main estimates and the strength of inference')
 equation(r'\ln(P_{Ci}/P_{0i})=\alpha+\beta v_i+\delta_2 Q2_i+\delta_3 Q3_i+\varepsilon_i.')
 para('The main model includes an intercept and Q2/Q3 indicators. Log returns limit the influence of very large gains, while raw returns remain in the descriptions. The slope is an association across companies. Both the final offer price and the first-day price reflect issuer characteristics, demand and the chosen offer structure.')
 table('Quarter-controlled slopes and month-jackknife intervals',['Outcome','Slope','CV3 SE','95% low','95% high','WCR p','Holm p'],[[LABELS[o],f3(q.loc[o].coefficient),f3(q.loc[o].cv3_se),f3(q.loc[o].cv3_ci_low),f3(q.loc[o].cv3_ci_high),f3(q.loc[o].wcr_p),f3(q.loc[o].historical_seven_outcome_holm_wcr_p)] for o in LABELS], 'N=43, nine listing-month clusters, four parameters. CV3 is the full-estimate-centered cluster jackknife; intervals use t(8). WCR is restricted wild cluster-t with all 512 Rademacher signs. Holm p retains the original seven-outcome family, including raw close, allocation and application return. No stars are used. Slope units are log-return units per one unit of fractional revision.')
 b=q.loc['log_close'];effect=np.expm1(.1*b.coefficient);lo=np.expm1(.1*b.cv3_ci_low);hi=np.expm1(.1*b.cv3_ci_high)
 para(f'A 10 percentage point difference in revision corresponds to a fitted {100*effect:.2f}% multiplicative difference in the close/offer price ratio. Its CV3 interval is {100*lo:.2f}% to {100*hi:.2f}%. This is not a change of the same number of percentage points in raw return. The revision standard deviation is {100*d.revision.std():.2f} percentage points; the corresponding fitted ratio difference is {100*np.expm1(b.coefficient*d.revision.std()):.2f}%.')
 table('Inference changes with the covariance method',['Outcome','HC3 p','CV3 p','CV3 Holm','WCR p','WCR Holm'],[[LABELS[o],f3(q.loc[o].hc3_p),f3(q.loc[o].cv3_t_p),f3(q.loc[o].historical_seven_outcome_holm_cv3_p),f3(q.loc[o].wcr_p),f3(q.loc[o].historical_seven_outcome_holm_wcr_p)] for o in LABELS], 'HC3 uses a t reference. Both Holm columns retain seven tests. The same estimates receive different uncertainty measures; this is not new independent evidence.')
 para('The intraday CV3 p-value is 0.013 before adjustment, but 0.088 after Holm adjustment. Its exact WCR p-value is 0.051 and its Holm WCR p-value is 0.355. This conflict is a material limitation with only nine clusters. The report therefore treats the intraday result as suggestive, and does not choose CV3 because it gives a smaller p-value. Failure to reject is also not proof of zero association.')
 table('All previously declared control designs',['Controls','Close','Opening','Intraday','HSI close'],[[label,*[f3(main[(main.model==key)&(main.outcome==o)].iloc[0].coefficient) for o in LABELS]] for key,label in [('revision_only','Revision only'),('quarter_controls','Quarter'),('launch_size_and_ah','Launch size and A+H'),('subscription_market_and_size','Subscription HSI and launch size')]],'All cells retain the same 43 firms. These are alternative small models, not a nested sequence. Full estimates, uncertainty and adjusted R-squared values are in stage_inference.csv.')
 page();section('3. Where the price difference occurs')
 equation(r'\ln(P_C/P_0)=\ln(P_O/P_0)+\ln(P_C/P_O).')
 para('The stage identity is exact for each firm. With the same OLS design, the close slope equals the opening slope plus the intraday slope: 1.598 = 0.874 + 0.723 after rounding. About 45.3% of the fitted slope is in the intraday component. This is accounting of an association, not a fraction of gains caused by late information.')
 gr=read('revision_stage_groups')
 table('Prices above and below the filed midpoint',['Final price','N','Revision %','Mean close %','Mean open %','Log day points'],[[('Above midpoint' if r.above_midpoint else 'Below midpoint'),int(r.n),pct(r.mean_revision),pct(r.mean_close),pct(r.mean_open),pct(r.mean_log_intraday)] for r in gr.itertuples()], 'Log day points are 100 times mean log(PC/PO), not mean simple intraday return. No final price equals the midpoint. The raw return mean need not describe a typical firm.')
 para('The below-midpoint firms have large mean opening gains but negative mean log intraday returns. The above-midpoint firms have positive mean log intraday returns. This locates a difference in subsequent trading. It does not show which traders caused it, or whether opening or closing prices were closer to fundamental value. Price discovery needs information or later valuation evidence, not only price changes.')
 robust=pd.read_csv(BASE/'steps/step04_estimates.csv')
 table('Robust estimators on the full sample',['Outcome','OLS','Median','Huber'],[[LABELS[o],*[f3(robust[(robust.design=='quarter_controls')&(robust.outcome==o)&(robust.estimator==est)].iloc[0].revision_coefficient) for est in ['OLS_HC3','Median','Huber']]] for o in LABELS], 'N=43 throughout. Median and Huber regressions estimate different functionals from the conditional mean. Their asymptotic SEs are not month-cluster robust. Their slopes cannot be added across stages as an exact decomposition.')
 loo=read('leave_one_month_out');lp=loo[loo.model.eq('quarter_controls')].pivot(index='deleted_month',columns='outcome',values='coefficient');info=read('cluster_information');info=info[info.model.eq('quarter_controls')].set_index('month')
 table('Delete one listing month at a time',['Deleted month','N kept','Close','Opening','Intraday','Info %'],[[m,int(43-info.loc[m,'n']),f3(r.log_close),f3(r.log_opening),f3(r.log_intraday),pct(info.loc[m,'information_share'])] for m,r in lp.iterrows()], 'All deleted-month designs remain full rank. Information share is the month share of squared revision residuals after quarter controls, measured in the full sample. No diagnostic exclusion replaces the main result.')
 para(f'All month-deletion slopes remain positive. Close slopes range from {lp.log_close.min():.3f} to {lp.log_close.max():.3f}. July holds 31.2% of the revision information. The inverse sum of squared information shares is {1/(info.information_share**2).sum():.2f}; this is a concentration diagnostic, not a replacement degrees of freedom. Sign stability is useful, but it does not establish a precise or causal effect.')
 page();section('4. Pricing dates, missing firms and market adjustment')
 para('No actual price-agreement date is newly certified in the current evidence record. The 36 recorded pricing anchors are expected-date proxies. Final-price publication timestamps are available for all 43 firms, but publication is not the time of agreement. The prior date search covered 29 complete local prospectuses and all 43 allotment texts. It did not establish that actual dates are absent from all public disclosures.')
 anchors=pd.read_csv(BASE/'steps/step02_matched_anchor_comparison.csv')
 # Column names follow the earlier date audit, not manually re-entered values.
 table('Matched companies distinguish date effects from selection',['Sample / anchor','N','Mean return %','Slope'],[[('All / raw close'),43,pct(d.close.mean()),f3(q.loc['log_close'].coefficient)],['All / subscription close',43,pct(d.mair_subscription.mean()),f3(q.loc['log_mair_subscription'].coefficient)]], 'The full seven-row anchor comparison is retained in Step 2. Publication-day and expected-date windows are sensitivity benchmarks, not verified holding periods.')
 para('On the same 36 proxy-available firms, the raw close slope is 3.419. Adjusted slopes range from 3.386 to 3.412, with adjusted mean returns from 66.05% to 66.18%. Thus, the apparent stronger relation comes mainly from excluding seven firms. It does not result from locating the market window more accurately. Keep all 43 firms in the headline analysis.')
 table('Two economically relevant counterexamples',['Code','Filed range HK$','Final HK$','Revision %','Open %','Close %'],[[r.code,f'{r.range_low:.2f}-{r.range_high:.2f}',f'{r.offer_price:.2f}',pct(r.revision),pct(r.opening),pct(r.close)] for r in d[d.code.isin(['2672.HK','3231.HK'])].itertuples()], 'The offer-price clauses in both complete official prospectuses were checked for this report. Final prices and raw opening/close inputs were also checked in the stored allotment evidence and market caches. Key source URLs and PDF hashes are retained in key_counterexample_evidence.csv.')
 para('These two firms account for 85.2% of the slope increase from 1.598 to 3.419 in exact deletion-order accounting across the seven missing-proxy firms. About 82.1% of that slope change occurs at opening. This diagnoses selection sensitivity. It is not evidence that these firms are errors, nor a reason to delete observations that contradict a preferred story.')
 bounds=read('anchor_slope_bounds')
 table('Date uncertainty without deleting any company',['Candidate anchor set','N','Slope low','Slope high','Mean low %','Mean high %'],[[('Subscription to publication' if r.window.startswith('subscription') else 'Prospectus to publication'),int(r.n),f3(r.coefficient_min),f3(r.coefficient_max),pct(r.mean_adjusted_return_min),pct(r.mean_adjusted_return_max)] for r in bounds.itertuples()], 'Each issuer may use any observed HSI daily close in the named set, including the latest close on or before its start date. All 43 firms remain; controls remain identical. These are sharp point-slope sensitivity bounds conditional on the assumed sets, not confidence intervals or certified actual pricing intervals.')
 para('Even the wider prospectus-to-publication set leaves the point slope between 1.351 and 1.744. That date effect is far smaller than the increase caused by selecting the 36 firms. It does not repair the wide statistical interval, and it cannot prove what the correct actual-date-adjusted coefficient is. HSI is a broad index; it does not remove sector shocks or issuer-specific news.')
 page();section('5. Range geometry, asymmetry and public information')
 equation(r'z=(P_0-P_L)/(P_H-P_L),\quad w=(P_H-P_L)/P_M,\quad v=w(z-1/2).')
 para('Revision combines location within the range with the width of that range. The mean width is 15.67% of midpoint, its median is 13.97%, and its range is 3.00%-46.15%. The final price is at the lower endpoint for 13 firms, inside for 13 and at the upper endpoint for 17. No recorded final price is outside its filed range. A result from these offers is therefore not a direct replication of evidence about pricing above a preliminary upper limit.')
 geom=read('range_geometry')
 table('Conditioning on range width',['Design / outcome','Slope','CV3 SE','WCR p','Holm p'],[[('Revision / ' if r.model=='revision_and_width' else 'Position / ')+LABELS[r.outcome],f3(r.coefficient),f3(r.cv3_se),f3(r.wcr_p),f3(r.holm_wcr_8_tests)] for r in geom.itertuples()], 'Both designs include width and Q2/Q3. N=43, five parameters. Position is centered at 0.5 and measured on a 0-1 scale. Position and revision slopes have different units. Holm covers all eight geometry tests; these extensions are exploratory.')
 para('The width-controlled close slope is 1.648, near the main 1.598. The centered-position close slope is 0.359. These signs suggest that width alone does not remove the association. They do not establish a structural price-adjustment parameter. The exploratory intraday geometry p-values are smaller before adjustment, but none passes the eight-test Holm family.')
 asym=read('asymmetry');rows=[]
 for o in LABELS:
  a=asym[(asym.outcome==o)&(asym.model=='asymmetric_revision')].set_index('term');diff=asym[(asym.outcome==o)&(asym.model=='positive_minus_negative_slope')].iloc[0]
  rows.append([LABELS[o],f3(a.loc['revision_positive'].coefficient),f3(a.loc['revision_negative'].coefficient),f3(diff.coefficient),f3(diff.wcr_p),f3(diff.holm_wcr_12_tests)])
 table('Exploratory positive versus negative revision slopes',['Outcome','Positive','Negative','Difference','Diff WCR p','Holm p'],rows,'Continuous hinge model with intercept and Q2/Q3; 21 positive and 22 negative revisions. The negative regressor retains its negative sign. Difference is positive slope minus negative slope. Holm covers both slopes and their difference for four outcomes: 12 tests.')
 para('The positive-revision close slope is 4.174; the negative-revision slope is -0.849. The difference has WCR p=0.172. None of the 12 asymmetry tests passes Holm adjustment; the smallest adjusted p-value is 0.797. The data are compatible with asymmetry, but cannot establish it. Different ranges of positive and negative revision and the small sample limit this test.')
 public=read('public_market_associations');r=public[public.outcome=='revision'].iloc[0]
 para(f'The prospectus-close to subscription-close HSI movement has a revision slope of {r.coefficient:.3f}, CV3 SE {r.cv3_se:.3f} and WCR p={r.wcr_p:.3f}, with quarter controls. Its close-return slope conditional on revision and quarter is 1.236 (WCR p=0.637). This does not show that public information is ignored or fully incorporated. The calendar window is not verified to precede actual agreement for every firm, and HSI movement is an incomplete information measure.')
 equation(r'\ln(P_C/P_M)=\ln(P_0/P_M)+\ln(P_C/P_0).')
 para('A shared-price problem also remains: with log(P0/PM) as regressor, the midpoint-close slope is exactly one plus the offer-close slope on the same design. That arithmetic is not an independent mechanism test. A final price is an endogenous choice, and the filed range can already contain expected demand information.')
 page();section('6. What the maximum-only offers add')
 para('The audit adds a separate disclosure regime, not 30 new midpoint revisions. These firms have an observed ceiling and a final price, so we can measure final price relative to ceiling. That measure is not revision relative to a two-sided midpoint.')
 equation(r'v_H=P_0/P_H-1.\qquad v_H=0\text{ means pricing at the ceiling.}')
 cap=read('ceiling_groups')
 table('Maximum-only offers: ceiling comparison',['Pricing position','N','Mean discount %','Mean close %','Median close %','Mean open %'],[[('At ceiling' if r.at_ceiling else 'Below ceiling'),int(r.n),pct(r.mean_ceiling_revision),pct(r.mean_close),pct(r.median_close),pct(r.mean_open)] for r in cap.itertuples()], 'Discount is negative below the ceiling. Twenty-six of 30 offers price at the ceiling. Only four offer ceiling-discount variation; all four are A+H. This comparison is descriptive.')
 cuts=read('maximum_only_panel');cuts=cuts[~cuts.at_ceiling]
 table('Every below-ceiling case',['Code','Ceiling HK$','Final HK$','Discount %','Opening %','Close %'],[[r.code,f'{r.range_high:.2f}',f'{r.offer_price:.2f}',pct(r.ceiling_revision),pct(r.opening),pct(r.close)] for r in cuts.itertuples()], 'These four observations cannot support a rich ceiling-revision regression or a general trading rule. Their mean close return is -0.16%, versus 9.68% for the at-ceiling group; this is not a causal discount effect.')
 overlap=read('route_disclosure_overlap');rows=[]
 for route,key,label in [(0,'two_sided_range','Non-A+H / range'),(1,'two_sided_range','A+H / range'),(1,'confirmed_maximum_only','A+H / maximum only'),(0,'confirmed_maximum_only','Other / maximum only')]:
  r=overlap[(overlap.ah==route)&(overlap.group==key)].iloc[0];rows.append([label,int(r.n),pct(r.mean_close),pct(r.median_close),pct(r.mean_open)])
 table('Listing-route overlap changes the comparison',['Route and disclosure','N','Mean close %','Median close %','Mean open %'],rows, 'The single non-A+H maximum-only case is Merdeka Gold depositary receipts, not a large comparable control group. Route categories are retained from the existing panel.')
 para('The all-firm mean close-return gap between range and maximum-only offers is 59.92 percentage points. Within A+H, it is only 2.28 percentage points: 11.16% versus 8.88%. This does not estimate a percentage of the gap caused by listing route; conditioning changes the population and leaves only nine range offers. It does show why a headline disclosure-format comparison is misleading. There is almost no non-A+H overlap in the maximum-only group.')
 para('For A+H issuers, the prospectus waiver often refers to the existing A-share market price as a pricing benchmark. Merdeka instead has an existing Indonesian share market. These source statements motivate benchmark and selection differences, but do not show equal A- and H-share valuations. Share classes, currency, investor access and market segmentation can differ. A rigorous cross-market valuation design would need dated reference-share prices and comparable conversion terms.')
 para('2041 is a separate caution. Its prospectus states a single price of HK$15.42, and its recorded close return is -42.93%. It belongs with single-price descriptions, not with maximum-only offers. The 30-firm maximum-only mean is now 8.36%, rather than the 6.71% mean for the old mixed 31-firm category. No source JSON or workbook was changed for this research overlay.')
 page();section('7. Findings, unresolved questions and supervisor brief')
 table('Which claims the current evidence supports',['Question','Assessment'],[
 ['Does midpoint revision predict later price gains?','Positive association; uncertain magnitude and adjusted inference.'],
 ['Were prices already raised during bookbuilding?','Not established by a final price above the filed midpoint.'],
 ['Are gains concentrated only at opening?','No. Opening and intraday components both enter the fitted relation.'],
 ['Does market-date adjustment reverse the point sign?','No within the stated candidate sets; actual dates remain unverified.'],
 ['Do contrary high-gain firms matter?','Yes. Two firms dominate the missing-proxy deletion effect.'],
 ['Does maximum-only disclosure cause lower returns?','Not identified; severe route imbalance and little ceiling variation.'],
 ['Has the current empirical topic been completed?','Yes as an association and sensitivity study; no causal mechanism claim.']
 ], 'The conclusions use the full main sample. Selected deletions, new covariance methods and additional tests do not replace the maintained inference.')
 para('The central economic puzzle remains: an offer price can be below the first-day trading price even after investors have expressed interest. Investor information rewards, constrained offer-price setting, issuer and intermediary objectives, scarce tradable supply, demand pressure and market segmentation can each generate this pattern. The present variables do not discriminate among them. Neither a positive slope nor a high opening price certifies market inefficiency or deliberate underpricing.')
 para('The first-day close is a market outcome, not an observed fundamental value. Opening auctions and thin tradable supply may change the measured stage pattern. Underwriter support can affect downside returns. Sector news and company quality can affect both revision and trading returns. Quarter controls are coarse; small models reduce parameter count but cannot remove these channels. No valid instrument, natural experiment or dated sequence of indicative price proposals is available here.')
 para('The next evidence with the highest value is a dated sequence of indicative prices and price-agreement statements for the range offers, plus a verified inventory of any range amendments. That would distinguish an actual change during marketing from a comparison with a filed midpoint. Order-flow or later valuation evidence would be needed to call the stage results price discovery. These are requirements for stronger causal research, not missing calculations that a larger regression can supply.')
 section('Supervisor discussion draft')
 para('We assess whether final offer-price revision is followed by further price gains in 113 Hong Kong Main Board IPOs listed in the first three quarters of 2026. Forty-three offers have usable two-sided ranges. A fresh source review separates 30 maximum-only offers from one single-price case. In the range sample, the quarter-controlled revision-close slope is positive, but its month-jackknife interval includes zero and the maintained multiple-test inference does not support a strong partial-adjustment claim. Opening and intraday components both contribute. Robust estimators and month deletions preserve the positive sign, while missing-date selection materially strengthens the estimate. Two below-midpoint, high-gain IPOs explain most of that selection effect. HSI anchor sensitivity is smaller when the companies are held fixed. Maximum-only offers provide limited ceiling-discount variation and differ sharply in listing route. We therefore report a robust sign pattern with uncertain magnitude, and a set of identification limits. We do not claim that prices were raised during subscription, that public information was ignored, or that the observed relation identifies investor-information compensation.')
 page();section('8. Technical appendix, provenance and replication')
 para('Month inference follows the cluster-jackknife approach in MacKinnon, Nielsen and Webb [2]. For each of nine listing months, re-estimate the complete design after deleting that month. Quarter indicators are re-estimated; they are not held at full-sample residual values. All retained designs are full rank.')
 equation(r'\widehat V_{CV3}=\frac{G-1}{G}\sum_{g=1}^{G}(\hat b_{(-g)}-\hat b)(\hat b_{(-g)}-\hat b)^{\prime},\qquad G=9.')
 para('The covariance centers the deletion coefficients on the full-sample estimate, not their mean. An independent block-residual sandwich check agrees to numerical tolerance. Tests also verify the known variance of an intercept-only mean with equal-size clusters, row-duplication invariance, and rejection of singular deleted-cluster designs. Exact Rademacher enumeration remains coarse with nine clusters; CV3 and WCR need not agree in this finite sample.')
 para('The anchor calculation fixes the companies and regression design. For each company, adjusted log return equals log close return minus log listing-day HSI close plus log candidate anchor close. The coefficient is a weighted sum of outcomes. Choose each allowed lower or upper outcome according to the sign of its coefficient weight to obtain sharp bounds within the sensitivity box.')
 equation(r'a^{\prime}=e_v^{\prime}(X^{\prime}X)^{-1}X^{\prime},\qquad \hat\beta=a^{\prime}y,\\ \beta_{\min}=\sum_{a_i\geq0}a_i y_i^-+\sum_{a_i<0}a_i y_i^+,\quad \beta_{\max}=\sum_{a_i\geq0}a_i y_i^++\sum_{a_i<0}a_i y_i^-.')
 para('Independent linear programming reproduces both bounds. The sets allow each company to select its own observed daily index anchor; the resulting worst cases are deliberately broad. They assume the chosen interval is relevant. They exclude unobserved intraday index levels and do not verify price agreement. No probability is attached to the bound endpoints.')
 para('Data provenance: The frozen 113-issuer panel is issuer_sample.csv in analysis/out/pricing_adjustment. The 31-issuer ledger in lower_bound_audit supplies official URLs, PDF pages and hashes. It is an analyst evidence record, not a formal source-writeback approval. The key two-company prospectus check is separate. Raw price and index series come from the documented Tencent market caches; official filings supply offer-price and disclosure evidence. Not every one of the 113 source fields was freshly certified in this topic.')
 para('Replication: Run analysis/pricing_topic1_completion_2026.py and then analysis/pricing_topic1_report.py with the project Python environment. The completion script needs the frozen panel, lower-bound ledger, earlier date ledger, baseline regression table and HSI cache. All are included or source-linked in the research package. It creates deterministic tables, manifests and checks. No investment simulation or random resampling is used. Earlier step scripts remain available for their separate source searches and estimator checks.')
 para('The report uses the existing editor filename to keep the open source stable. Its title and contents cover Topic 1 only. The former joint-report generator no longer overwrites this completed report automatically. Topic 2 and Topic 3 require separate reports after their own research is complete. Source-field corrections, expanded cohorts and later revisions can change these estimates; the cutoff and input hashes delimit the present result.')
 section('References and source records')
 refs=[('1. Hanley, K. W. (1993). The underpricing of initial public offerings and the partial adjustment phenomenon. Journal of Financial Economics 34, 231-250.','https://business.lehigh.edu/sites/default/files/2019-08/7%20hanley_1993_jfe_0.pdf'),('2. MacKinnon, J. G., Nielsen, M. O., and Webb, M. D. (2023). Fast and reliable jackknife and bootstrap methods for cluster-robust inference.','https://arxiv.org/abs/2301.04527'),('3. Official Medcaptain prospectus: single quoted price, PDF pages 2 and 293.','https://www1.hkexnews.hk/listedco/listconews/sehk/2026/0828/2026082800009.pdf'),('4. Official Baige prospectus: two-sided offer-price terms, PDF page 2.','https://www1.hkexnews.hk/listedco/listconews/sehk/2026/0618/2026061800045.pdf')]
 for text,url in refs:raw.append(r'{\footnotesize '+esc(text)+' '+r'\href{'+url+r'}{Source}.}\par'+'\n');md.append(text+' [Source]('+url+')\n')
 para('The Topic 1 result folder contains the issuer panel, all model estimates, cluster diagnostics, date sensitivity bounds, disclosure comparisons and source checks. Its README maps each result file to its research purpose. The run manifest records input hashes, package versions, checks and study limits.')
 preamble=r'''\documentclass[10pt,a4paper]{article}
\usepackage[margin=17mm,headheight=14pt]{geometry}
\usepackage[T1]{fontenc}\usepackage{lmodern}
\usepackage{amsmath,booktabs,array,tabularx}
\usepackage[hidelinks]{hyperref}\usepackage{fancyhdr}\usepackage{titlesec}
\titleformat{\section}{\normalsize\bfseries}{}{0pt}{}
\titlespacing*{\section}{0pt}{7pt}{3pt}
\setlength{\parindent}{0pt}\setlength{\parskip}{3pt}\setlength{\tabcolsep}{3.5pt}
\setlength{\emergencystretch}{2em}
\pagestyle{fancy}\fancyhf{}\fancyhead[L]{\small Topic 1: Pricing adjustment and first-day returns}
\fancyhead[R]{\small Cutoff: 30 September 2026}\fancyfoot[C]{\small\thepage}
\renewcommand{\headrulewidth}{0pt}
\hypersetup{pdftitle={HK IPO 2026 Topic 1: Pricing Adjustment and First-Day Returns},pdfauthor={}}
\begin{document}
{\LARGE\bfseries Pricing Adjustment and First-Day Returns}\par\addvspace{4pt}
{\large Topic 1 -- Hong Kong Main Board IPOs in 2026}\par\addvspace{4pt}
'''
 TEX.write_text(preamble+'\n'.join(raw)+'\n\\end{document}\n')
 MD.write_text('# Topic 1: Pricing Adjustment and First-Day Returns\n\n'+'\n'.join(md))
 manifest=json.loads((OUT/'run_manifest.json').read_text());manifest['report_scope']='Topic 1 only; current-sample empirical assessment complete, causal mechanism unverified';manifest['report_tables']=counter
 manifest['report_source_sha256']=hashlib.sha256(TEX.read_bytes()).hexdigest();manifest['report_builder_sha256']=hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
 (OUT/'run_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
 print('Wrote existing editor source:',TEX,'Tables:',counter)
if __name__=='__main__':write_report()
